<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AssemblyName>SailwindFastForward</AssemblyName>
    <Version>1.1.1</Version>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <GameDir Condition="'$(GameDir)' == ''">C:\Steam Games\steamapps\common\Sailwind</GameDir>
    <BepInExCore Condition="'$(BepInExCore)' == ''">$(MSBuildThisFileDirectory)..\.local\references</BepInExCore>
    <Managed>$(GameDir)\Sailwind_Data\Managed</Managed>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="BepInEx" HintPath="$(BepInExCore)\BepInEx.dll" Private="false" />
    <Reference Include="0Harmony" HintPath="$(BepInExCore)\0Harmony.dll" Private="false" />
    <Reference Include="Assembly-CSharp" HintPath="$(Managed)\Assembly-CSharp.dll" Private="false" />
    <Reference Include="Oculus.VR" HintPath="$(Managed)\Oculus.VR.dll" Private="false" />
    <Reference Include="UnityEngine" HintPath="$(Managed)\UnityEngine.dll" Private="false" />
    <Reference Include="UnityEngine.CoreModule" HintPath="$(Managed)\UnityEngine.CoreModule.dll" Private="false" />
    <Reference Include="UnityEngine.InputModule" HintPath="$(Managed)\UnityEngine.InputModule.dll" Private="false" />
    <Reference Include="UnityEngine.IMGUIModule" HintPath="$(Managed)\UnityEngine.IMGUIModule.dll" Private="false" />
    <Reference Include="UnityEngine.TextRenderingModule" HintPath="$(Managed)\UnityEngine.TextRenderingModule.dll" Private="false" />
  </ItemGroup>
</Project>
